on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Tests
      id: test
      run: |

        TWTOKEN=$(curl -S -X POST 'https://id.twitch.tv/oauth2/token' \
            -H 'Content-Type: application/x-www-form-urlencoded' \
            -d "client_id=${{ secrets.TWITCH_CLIENT }}&client_secret=${{ secrets.TWITCH_SECRET }}&grant_type=client_credentials" | jq  -r .access_token)


        curl -S -X GET 'https://api.twitch.tv/helix/streams?type=live&user_login=cailloute' \
            -H "Authorization: Bearer ${TWTOKEN}" \
            -H "Client-Id: ${{ secrets.TWITCH_CLIENT }}" >stream

    - name: Choose Site to Deploy
      id: choose_site
      run: |
        ONLINE=$(jq '.data[]|select(.user_login=="cailloute").started_at' stream)
        { [[ "$ONLINE" == "" ]] && echo site=non || echo site=oui ; } >> $GITHUB_ENV

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.site }}

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
